### ISSUE TITLE
Add support for conversion of non-DAIDE order messages to DAIDE style

### ISSUE THREAD

**Issue by kartik2112** [trigaten/DAIDE#3]
When XDO is called over a message such as `F BRE - MAO`, it encapsulates this as it is. Instead, modify the code such that it would verify this grammar and convert this to `(FRA FLT BRE) MTO MAO`

**Comment by trigaten** [comment]
@kartik2112 is this alternative grammar explicitly defined in a spec? 

Also you may want to put this issue on DAIDE++ since I want to deprecate this library in favor of it.

**Comment by kartik2112** [comment]
Yes, the order examples are mentioned here: https://github.com/SHADE-AI/daidepp/blob/main/daide-syntax.pdf. Page 5.

**Comment by kartik2112** [comment]
I am not sure if order to DAIDE message generation is currently being done in the DAIDE++ library which makes yours still useful in parts.

**Comment by trigaten** [comment]
@kartik2112 Im not seeing `F BRE - MAO` in the DAIDE spec. Is there a spec for these types of orders?

**Comment by kartik2112** [comment]
No, `F BRE - MAO` is not DAIDE syntax but the dipnet bot we have been using outputs orders in this format. Hence, it is convenient to have an intermediate converter. Or are you suggesting we keep this converter local to `baseline_bots`?

**Comment by trigaten** [comment]
> Or are you suggesting we keep this converter local to baseline_bots?

I am not sure of the best place for the converter. Either baseline bots or this repo would likely be fine.

**Comment by trigaten** [comment]
If you have time/the need to build it out, it would likely be easiest to put it in baseline bots.

**Comment by trigaten** [comment]
Closing as this is resolved in baseline_bots
